In [3]:
import numpy as np

 ### Numpy array

In [6]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [8]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [16]:
arr.ndim

1

In [18]:
array_m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
np_array_m = np.array(array_m)
np_array_m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np_array_m.ndim

2

In [26]:
# Using arange() function to create own array

np.arange(0, 11, dtype = np.float32)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

In [28]:
np.arange(0, 11, 2, dtype = np.int32)

array([ 0,  2,  4,  6,  8, 10], dtype=int32)

In [30]:
# Use zero()

np.zeros(3)

array([0., 0., 0.])