In [3]:
import numpy as np

 ### Numpy array

In [6]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [8]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [16]:
arr.ndim

1

In [18]:
array_m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
np_array_m = np.array(array_m)
np_array_m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np_array_m.ndim

2

In [26]:
# Using arange() function to create own array

np.arange(0, 11, dtype = np.float32)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

In [28]:
np.arange(0, 11, 2, dtype = np.int32)

array([ 0,  2,  4,  6,  8, 10], dtype=int32)

In [30]:
# Use zeros() function

np.zeros(3)

array([0., 0., 0.])

In [32]:
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
# Using ones() function

np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [38]:
# linspace() function

np.linspace(0, 5, 100, dtype = np.float32)

array([0.        , 0.05050505, 0.1010101 , 0.15151516, 0.2020202 ,
       0.25252524, 0.3030303 , 0.35353535, 0.4040404 , 0.45454547,
       0.5050505 , 0.5555556 , 0.6060606 , 0.65656567, 0.7070707 ,
       0.75757575, 0.8080808 , 0.85858583, 0.90909094, 0.959596  ,
       1.010101  , 1.060606  , 1.1111112 , 1.1616162 , 1.2121212 ,
       1.2626263 , 1.3131313 , 1.3636364 , 1.4141414 , 1.4646465 ,
       1.5151515 , 1.5656565 , 1.6161616 , 1.6666666 , 1.7171717 ,
       1.7676767 , 1.8181819 , 1.8686869 , 1.919192  , 1.969697  ,
       2.020202  , 2.070707  , 2.121212  , 2.1717172 , 2.2222223 ,
       2.2727273 , 2.3232324 , 2.3737373 , 2.4242425 , 2.4747474 ,
       2.5252526 , 2.5757575 , 2.6262627 , 2.6767676 , 2.7272727 ,
       2.7777777 , 2.8282828 , 2.878788  , 2.929293  , 2.979798  ,
       3.030303  , 3.0808082 , 3.131313  , 3.1818182 , 3.2323232 ,
       3.2828283 , 3.3333333 , 3.3838384 , 3.4343433 , 3.4848485 ,
       3.5353534 , 3.5858586 , 3.6363637 , 3.6868687 , 3.73737

In [40]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
# Use this methond for create random number array

np.random.rand(6, 5)

array([[0.61486662, 0.16543047, 0.44335454, 0.50132597, 0.29080301],
       [0.27634298, 0.99039789, 0.45220809, 0.34382093, 0.46806483],
       [0.05012981, 0.33421804, 0.70542422, 0.16064699, 0.89319754],
       [0.00912432, 0.07671449, 0.8840904 , 0.19207949, 0.22279635],
       [0.89768972, 0.48339037, 0.21647876, 0.10092267, 0.57664775],
       [0.79720595, 0.3431966 , 0.23474819, 0.22148128, 0.78165537]])

In [46]:
# Use this methond we can create a random normaldistribution number 

np.random.randn(5, 6)

array([[-1.686535  ,  0.08351865, -0.38583373,  0.49168058, -0.38150388,
        -0.73437955],
       [-0.13322978,  0.37141334,  0.34877282,  0.37979255, -1.50414514,
        -1.70651001],
       [ 0.1122289 , -0.5734503 ,  0.44038344,  0.05633813,  0.94959961,
         0.05860369],
       [ 1.06152952, -0.8631943 ,  0.52682839, -0.05099809, -0.35069587,
         0.96431403],
       [ 0.55997815, -1.06875711, -0.73843802, -0.87463654, -0.71790421,
        -0.41471165]])

In [48]:
# Use this one for create a random integer number

np.random.randint(1, 100, 10)

array([87, 20, 84, 47, 20, 93,  8, 77, 60, 45])

In [76]:
arr = np.arange(25)

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
randarr = np.random.randint(0, 50, 10)

In [68]:
randarr

array([10, 41, 26, 15,  7,  6, 43, 18, 40,  9])

In [80]:
# Use this function to reshape array

arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
randarr.max()

43

In [84]:
randarr.min()

6

In [86]:
randarr.argmax()

6

In [88]:
randarr.argmin()

5

In [92]:
randarr.dtype

dtype('int64')

In [94]:
from numpy.random import randint

randint(0, 100, 20)

array([21,  2,  6, 93, 48, 85, 85, 17, 42, 54,  5, 67, 45, 78, 97, 80, 37,
        1, 99, 46])

### Numpy indexing and selection

In [98]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr[8]

8

In [102]:
arr[1:5]

array([1, 2, 3, 4])

In [104]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [106]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [108]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [110]:
# borcasting

arr[:5] = 100

In [112]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [114]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
slice_of_arr = arr[:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [118]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [124]:
arr_copy = arr.copy()

In [126]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [128]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [132]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [134]:
# Indexing 2D array

arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [138]:
arr_2d_copy = arr_2d.copy()

In [142]:
arr_2d[0][0]

5

In [144]:
arr_2d[2][1]

40

In [146]:
arr_2d[2, 1]

40

In [148]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [152]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [158]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [160]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [162]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [164]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [166]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [172]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])