In [3]:
import numpy as np

 ### Numpy array

In [6]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [8]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [16]:
arr.ndim

1

In [18]:
array_m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
np_array_m = np.array(array_m)
np_array_m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np_array_m.ndim

2

In [26]:
# Using arange() function to create own array

np.arange(0, 11, dtype = np.float32)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

In [28]:
np.arange(0, 11, 2, dtype = np.int32)

array([ 0,  2,  4,  6,  8, 10], dtype=int32)

In [30]:
# Use zeros() function

np.zeros(3)

array([0., 0., 0.])

In [32]:
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
# Using ones() function

np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [38]:
# linspace() function

np.linspace(0, 5, 100, dtype = np.float32)

array([0.        , 0.05050505, 0.1010101 , 0.15151516, 0.2020202 ,
       0.25252524, 0.3030303 , 0.35353535, 0.4040404 , 0.45454547,
       0.5050505 , 0.5555556 , 0.6060606 , 0.65656567, 0.7070707 ,
       0.75757575, 0.8080808 , 0.85858583, 0.90909094, 0.959596  ,
       1.010101  , 1.060606  , 1.1111112 , 1.1616162 , 1.2121212 ,
       1.2626263 , 1.3131313 , 1.3636364 , 1.4141414 , 1.4646465 ,
       1.5151515 , 1.5656565 , 1.6161616 , 1.6666666 , 1.7171717 ,
       1.7676767 , 1.8181819 , 1.8686869 , 1.919192  , 1.969697  ,
       2.020202  , 2.070707  , 2.121212  , 2.1717172 , 2.2222223 ,
       2.2727273 , 2.3232324 , 2.3737373 , 2.4242425 , 2.4747474 ,
       2.5252526 , 2.5757575 , 2.6262627 , 2.6767676 , 2.7272727 ,
       2.7777777 , 2.8282828 , 2.878788  , 2.929293  , 2.979798  ,
       3.030303  , 3.0808082 , 3.131313  , 3.1818182 , 3.2323232 ,
       3.2828283 , 3.3333333 , 3.3838384 , 3.4343433 , 3.4848485 ,
       3.5353534 , 3.5858586 , 3.6363637 , 3.6868687 , 3.73737